swagger: "2.0"
info:
  description: "A micro-service approach"
  version: "0.1"
  title: "Mandatory Assignment 1"
paths:
  /student:
    post:
      tags:
        - "student"
      summary: "Add a new student to the system"
      operationId: "addStudent"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/Student"
      responses:
        "405":
          description: "Invalid input"
  /student/{student_id}:
    get:
      tags:
        - "student"
      summary: "Find student by ID"
      description: "Returns a single student"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "student_id"
          in: "path"
          description: "ID of student to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "400":
            description: "Invalid ID supplied"
        "200":
          description: "success"
          schema:
              $ref: "#/definitions/Student"
    put:
      tags:
        - "student"
      summary: "Update an existing student"
      operationId: "updateStudent"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
        - name: "student_id"
          in: "path"
          description: "ID of student to return"
          required: true
          type: "integer"
          format: "int64"
        - in: "body"
          name: "body"
          description: "The modified student object"
          required: true
          schema:
            $ref: "#/definitions/Student"
      responses:
        "404":
          description: "Student not found"
    delete:
      tags:
      - "student"
      summary: "Deletes a student"
      operationId: "deleteStudent"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "student_id"
        in: "path"
        description: "Course ID to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Student not found"
  /student/{student_id}/workload:
    get:
      tags:
      - "student"
      summary: "A sum of the ECTS associated with the student's courses"
      operationId: "getWorkload"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "student_id"
        in: "path"
        description: "ID of student to get the workload for"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Student not found"
        "200":
          description: "success"
          schema:
            type: "integer"
definitions:
  Student:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      course_workload:
        type: "integer"