swagger: "2.0"
info:
  description: "A monolithic approach"
  version: "0.1"
  title: "Mandatory Assignment 1"
paths:
  /student:
    post:
      tags:
        - "student"
      summary: "Add a new student to the system"
      operationId: "addStudent"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/Student"
      responses:
        "405":
          description: "Invalid input"
  /student/{student_id}:
    get:
      tags:
        - "student"
      summary: "Find student by ID"
      description: "Returns a single student"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "student_id"
          in: "path"
          description: "ID of student to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "400":
            description: "Invalid ID supplied"
        "200":
          description: "success"
          schema:
              $ref: "#/definitions/Student"
    put:
      tags:
        - "student"
      summary: "Update an existing student"
      operationId: "updateStudent"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
        - name: "student_id"
          in: "path"
          description: "ID of student to return"
          required: true
          type: "integer"
          format: "int64"
        - in: "body"
          name: "body"
          description: "The modified student object"
          required: true
          schema:
            $ref: "#/definitions/Student"
      responses:
        "404":
          description: "Student not found"
    delete:
      tags:
      - "student"
      summary: "Deletes a student"
      operationId: "deleteStudent"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "student_id"
        in: "path"
        description: "Course ID to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Student not found"
  /student/{student_id}/workload:
    get:
      tags:
      - "student"
      summary: "A sum of the ECTS associated with the student's courses"
      operationId: "getWorkload"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "student_id"
        in: "path"
        description: "ID of student to get the workload for"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Student not found"
        "200":
          description: "success"
          schema:
            type: "integer"
          
  /course:
    post:
        tags:
          - "course"
        summary: "Add a new course to the system"
        operationId: "addCourset"
        consumes:
          - "application/json"
          - "application/xml"
        produces:
          - "application/xml"
          - "application/json"
        parameters:
          - in: "body"
            name: "body"
            required: true
            schema:
              $ref: "#/definitions/Course"
        responses:
          "405":
            description: "Invalid input"
  /course/{course_id}:
    get:
      tags:
        - "course"
      summary: "Find course by ID"
      description: "Returns a single course"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "course_id"
          in: "path"
          description: "ID of course to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "400":
            description: "Invalid ID supplied"
        "200":
          description: "success"
          schema:
              $ref: "#/definitions/Course"
    put:
      tags:
        - "course"
      summary: "Update an existing course"
      operationId: "updateCourse"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "course_id"
          in: "path"
          description: "ID of course update"
          required: true
          type: "integer"
          format: "int64"
        - in: "body"
          name: "body"
          description: "The modified course object"
          required: true
          schema:
            $ref: "#/definitions/Course"
      responses:
        "404":
          description: "Course not found"
    delete:
      tags:
      - "course"
      summary: "Deletes a course"
      operationId: "deleteCourse"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "course_id"
        in: "path"
        description: "Course ID to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Course not found"
  /course/{course_id}/teachers:
    get:
      tags:
      - "course"
      summary: "Return all the teacher IDs teaching a course"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "course_id"
        in: "path"
        description: "ID of the course to get the teachers for"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "404":
          description: "Course not found"
        "200":
            description: "success"
            schema:
              type: "array"
              items: 
                type: "integer"
                format: "int64"
  /course/{course_id}/satisfaction_rating:
    get:
      tags:
        - "course"
      summary: "Returns a course's satisfaction rating by ID"
      description: "Returns an integer"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "course_id"
          in: "path"
          description: "ID of course to return the sastisfaction rating of"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "400":
            description: "Invalid ID supplied"
        "200":
          description: "success"
          schema:
            type: "integer"
  /teacher:
    post:
      tags:
        - "teacher"
      summary: "Add a new teacher to the system"
      operationId: "addTeacher"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/Teacher"
      responses:
        "405":
          description: "Invalid input"
  /teacher/{teacher_id}:
    get:
      tags:
        - "teacher"
      summary: "Find teacher by ID"
      description: "Returns a single teacher"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "teacher_id"
          in: "path"
          description: "ID of teacher to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "400":
            description: "Invalid ID supplied"
        "200":
          description: "success"
          schema:
            $ref: "#/definitions/Teacher"
    put:
      tags:
        - "teacher"
      summary: "Update an existing teacher"
      operationId: "updateTeacher"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
        - name: "teacher_id"
          in: "path"
          description: "ID of teacher to return"
          required: true
          type: "integer"
          format: "int64"
        - in: "body"
          name: "body"
          description: "The modified teacher object"
          required: true
          schema:
            $ref: "#/definitions/Teacher"
      responses:
        "404":
          description: "Teacher not found"
    delete:
      tags:
      - "teacher"
      summary: "Deletes a teacher"
      operationId: "deleteTeacher"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "teacher_id"
        in: "path"
        description: "Teacher ID to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Teacher not found"
definitions:
  Student:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      course_workload:
        type: "integer"
  Course:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
      teachers:
        type: "array"
        items:
          type: "integer"
          format: "int64"
      ects:
        type: "integer"
      satisfaction_score:
        type: "integer"
  Teacher:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      popularity_rating:
        type: "integer"
    