/*
 * Mandatory Assignemnt 1
 *
 * Mandotory Assignment 1
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"AddCourse",
		strings.ToUpper("Post"),
		"/course",
		AddCourse,
	},

	Route{
		"CourseCourseIdGet",
		strings.ToUpper("Get"),
		"/course/{course_id}",
		CourseCourseIdGet,
	},

	Route{
		"CourseCourseIdSatisfactionRatingGet",
		strings.ToUpper("Get"),
		"/course/{course_id}/satisfaction_rating",
		CourseCourseIdSatisfactionRatingGet,
	},

	Route{
		"CourseCourseIdTeachersGet",
		strings.ToUpper("Get"),
		"/course/{course_id}/teachers",
		CourseCourseIdTeachersGet,
	},

	Route{
		"DeleteCourse",
		strings.ToUpper("Delete"),
		"/course/{course_id}",
		DeleteCourse,
	},

	Route{
		"UpdateCourse",
		strings.ToUpper("Put"),
		"/course/{course_id}",
		UpdateCourse,
	},
}
