/*
 * Mandatory Assignemnt 1
 *
 * Mandotory Assignment 1
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

func NewCourse(id int64, title string, teachers []int64, ects int32, satisfactionScore int32) Course {
	return Course{
		Id:                id,
		Title:             title,
		Teachers:          teachers,
		Ects:              ects,
		SatisfactionScore: satisfactionScore,
	}
}

type Course struct {
	Id int64 `json:"id,omitempty"`

	Title string `json:"title,omitempty"`

	Teachers []int64 `json:"teachers,omitempty"`

	Ects int32 `json:"ects,omitempty"`

	SatisfactionScore int32 `json:"satisfaction_score,omitempty"`
}
